### ISSUE TITLE
Fix inconsistencies in HCV1a.json example

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#32]
The example [HCV1a.json](https://github.com/biocompute-objects/BCO_Specification/blob/master/HCV1a.json) includes some keys not defined elsewhere (`uri`, `sha1_chksum`):

```json
            {
                "name": "HIVE-heptagon", 
                "version": "albinoni.2",
                "uri": {
                    "address": "https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-heptagon&cmdMode=-",
                    "access_time": "2017-01-24T09:40:17-0500",
                    "sha1_chksum": null
}
```

While the BCO do permit arbitrary keys for [software_prerequisites](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#256-algorithmic-tools-and-software-prerequisites-software_prerequisites) the example should only use values defined in the spec.

One `error_domain` is listed twice, with and without spaces (and different values!):

```json
     "false positive mutation calls discovery": "<0.0005", 
     "false_positive_mutation_calls_discovery": "<0.00005", 
```

Access to FTP is used without hostname, but this behavior is not defined in [domain_prerequisites](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#257-domain-prerequisites-domain_prerequisites)

```json
            {
                "name": "access to ftp", 
                "url": "ftp://:22/"
}, 
```

Similarly this abstract example should be removed as this "concrete" example don't want to access the `protocol` protocol:

```json
				"name": "generic name",
			    "url": "protocol://domain:port/application/path"
}
```

Access to HIVE should presumably extend beyond the login page:

```json
            {
                "name": "HIVE", 
                "url": "https://hive.biochemistry.gwu.edu/dna.cgi?cmd=login"
}, 
```

so here the URL should be chopped at first `/`

The `script_access_type` is `text`, yet a URI is provided for `script`:

```json
        "script_access_type": "text",
        "script": ["https://example.com/workflows/antiviral_resistance_detection_hive.py"],
```

The [script driver](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#255-script-driver-script_driver) `manual` is undefined:

```json
"script_driver": "manual",
```

The input/output URI examples have invalid hostname `hive.biochemistry.gwu.edudata`. These should either be neutral on http://example.com/ or actually work.

```
 "input_list": [
                        {
                            "address": "https://hive.biochemistry.gwu.edudata/514769/dnaAccessionBased.csv",
                            "access_time": "2017-01-24T09:40:17-0500"
                        }
], 
```

Some of the Sequence Ontology examples are missing `SO:` and thus don't work with http://identifiers.org/so/ according to [external references](https://github.com/biocompute-objects/BCO_Specification/blob/master/external-references.md) expansion.

```json
 "structured_name": "HCV1a [taxonomy:31646] ledipasvir 
       [pubchem.compound:67505836] resistance SNP 
       [so:0000694] detection",

"name": "Sequence Ontology",
"ids": ["0000048"], 

  "usability_domain": [
        "Identify baseline single nucleotide polymorphisms SNPs [SO:0000694], insertions [so:SO:0000667], and deletions [so:SO:0000045] that correlate with reduced ledipasvir [pubchem.compound:67505836] antiviral drug efficacy in Hepatitis C virus subtype 1 [taxonomy:31646]", 
],
```

**Comment by HadleyKing** [comment]
* [ ] The example [HCV1a.json](https://github.com/biocompute-objects/BCO_Specification/blob/master/HCV1a.json) includes some keys not defined elsewhere (`uri`, `sha1_chksum`):
 
 
* [ ] While the BCO do permit arbitrary keys for [software_prerequisites](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#256-algorithmic-tools-and-software-prerequisites-software_prerequisites) the example should only use values defined in the spec.
 
* [ ] One `error_domain` is listed twice, with and without spaces (and different values!):
 
* [ ] Access to FTP is used without hostname, but this behavior is not defined in [domain_prerequisites](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#257-domain-prerequisites-domain_prerequisites)
 
* [ ]  Similarly this abstract example should be removed as this "concrete" example don't want to access the `protocol` protocol:
 
* [ ] Access to HIVE should presumably extend beyond the login page. so here the URL should be chopped at first `/`
 
* [ ]  The `script_access_type` is `text`, yet a URI is provided for `script`:
 
* [ ]  The [script driver](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#255-script-driver-script_driver) `manual` is undefined:

* [ ] The input/output URI examples have invalid hostname `hive.biochemistry.gwu.edudata`. These should either be neutral o http://example.com/ or actually work.

* [ ]  Some of the Sequence Ontology examples are missing `SO:` and thus don't work with http://identifiers.org/so/ according to [external references](https://github.com/biocompute-objects/BCO_Specification/blob/master/external-references.md) expansion.
